# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Tech Notes
tagline:          'architecture, systems, cloud, devops and some code'
description:      'Architecture, systems, cloud, devops and some code.. <br /> from <a href="https://www.linkedin.com/in/naamancampbell/" target="_blank">@NaamanCampbell</a>'
url:              http://tech.clancampbell.id.au
baseurl:          /

author:
  name:           'Naaman Campbell'
  url:            https://www.linkedin.com/in/naamancampbell/

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/naamancampbell/naamancampbell.github.io
